quiet: true

skip-check:
  - CKV_AWS_158   # Ensure that CloudWatch Log Group is encrypted by KMS.
  - CKV_AWS_272   # Ensure AWS Lambda function is configured to validate code-signing (not required for handson)
  - CKV_AWS_115   # Ensure that AWS Lambda function is configured for function-level concurrent execution limit (not required for handson)
  - CKV_AWS_173   # Check encryption settings for Lambda environmental variable (not required for handson)
  - CKV_AWS_117   # Ensure that AWS Lambda function is configured inside a VPC (explicitly not using VPC per requirements)
  - CKV_AWS_116   # Ensure that AWS Lambda function is configured for a Dead Letter Queue(DLQ) (not required for handson)
  - CKV_AWS_50    # X-Ray tracing is enabled for Lambda (not required for handson)
  - CKV_AWS_258   # Ensure that Lambda function URLs AuthType is not None (public access required per requirements)
  - CKV_AWS_338   # Ensure CloudWatch log groups retains logs for at least 1 year (7 days retention per requirements)
